// 営業トラブルアラートのダミーデータ（30件）
export const alertsData = [
  // 営業側のトラブルキーワード
  {
    id: "ALT-001",
    datetime: "2024-01-15 09:30:00",
    keyword: "お見積りが完成次第送付します",
    department: "営業部",
    person: "佐藤一郎",
    level: "high",
    status: "pending",
    category: "sales",
    description: "見積もり送付の約束から2週間経過",
    customerName: "田中様",
    customerCompany: "ABC商事株式会社",
    customerEmail: "tanaka@abc-corp.co.jp",
  },
  {
    id: "ALT-002",
    datetime: "2024-01-15 10:15:00",
    keyword: "来週までに回答します",
    department: "インサイドセールス",
    person: "田中花子",
    level: "medium",
    status: "in_progress",
    category: "sales",
    description: "回答期限が曖昧で追跡困難",
    customerName: "山田様",
    customerCompany: "XYZ株式会社",
    customerEmail: "yamada@xyz-inc.co.jp",
  },
  {
    id: "ALT-003",
    datetime: "2024-01-15 11:00:00",
    keyword: "上司に確認してから連絡します",
    department: "営業部",
    person: "山田太郎",
    level: "medium",
    status: "pending",
    category: "sales",
    description: "決裁権限の不明確さを示唆",
    customerName: "鈴木様",
    customerCompany: "DEF株式会社",
    customerEmail: "suzuki@def-corp.co.jp",
  },
  {
    id: "ALT-004",
    datetime: "2024-01-15 13:45:00",
    keyword: "検討中です",
    department: "AM部",
    person: "鈴木次郎",
    level: "low",
    status: "resolved",
    category: "sales",
    description: "具体的な検討内容が不明",
    customerName: "高橋様",
    customerCompany: "GHI株式会社",
    customerEmail: "takahashi@ghi-corp.co.jp",
  },
  {
    id: "ALT-005",
    datetime: "2024-01-15 14:20:00",
    keyword: "予算の都合で難しいかもしれません",
    department: "営業部",
    person: "高橋美咲",
    level: "high",
    status: "pending",
    category: "sales",
    description: "予算不足の可能性を示唆",
    customerName: "伊藤様",
    customerCompany: "JKL株式会社",
    customerEmail: "ito@jkl-corp.co.jp",
  },
  {
    id: "ALT-006",
    datetime: "2024-01-15 15:30:00",
    keyword: "他社と比較検討中です",
    department: "インサイドセールス",
    person: "伊藤健一",
    level: "medium",
    status: "in_progress",
    category: "sales",
    description: "競合他社との比較段階",
    customerName: "渡辺様",
    customerCompany: "MNO株式会社",
    customerEmail: "watanabe@mno-corp.co.jp",
  },
  {
    id: "ALT-007",
    datetime: "2024-01-15 16:10:00",
    keyword: "社内で調整が必要です",
    department: "営業部",
    person: "渡辺雅子",
    level: "medium",
    status: "pending",
    category: "sales",
    description: "社内調整の長期化リスク",
    customerName: "加藤様",
    customerCompany: "PQR株式会社",
    customerEmail: "kato@pqr-corp.co.jp",
  },
  {
    id: "ALT-008",
    datetime: "2024-01-16 09:00:00",
    keyword: "申し訳ございませんが",
    department: "AM部",
    person: "加藤直樹",
    level: "high",
    status: "pending",
    category: "sales",
    description: "謝罪から始まる問題発生の兆候",
    customerName: "小林様",
    customerCompany: "STU株式会社",
    customerEmail: "kobayashi@stu-corp.co.jp",
  },
  {
    id: "ALT-009",
    datetime: "2024-01-16 10:30:00",
    keyword: "想定より時間がかかっています",
    department: "営業部",
    person: "小林恵子",
    level: "medium",
    status: "in_progress",
    category: "sales",
    description: "プロジェクト遅延の可能性",
    customerName: "中村様",
    customerCompany: "VWX株式会社",
    customerEmail: "nakamura@vwx-corp.co.jp",
  },
  {
    id: "ALT-010",
    datetime: "2024-01-16 11:45:00",
    keyword: "確認が取れ次第ご連絡します",
    department: "インサイドセールス",
    person: "中村和也",
    level: "low",
    status: "resolved",
    category: "sales",
    description: "確認作業の遅延リスク",
    customerName: "森田様",
    customerCompany: "YZA株式会社",
    customerEmail: "morita@yza-corp.co.jp",
  },
  {
    id: "ALT-011",
    datetime: "2024-01-16 13:20:00",
    keyword: "少々お待ちください",
    department: "営業部",
    person: "森田智子",
    level: "low",
    status: "pending",
    category: "sales",
    description: "待機時間の長期化懸念",
    customerName: "清水様",
    customerCompany: "BCD株式会社",
    customerEmail: "shimizu@bcd-corp.co.jp",
  },
  {
    id: "ALT-012",
    datetime: "2024-01-16 14:15:00",
    keyword: "担当者が不在のため",
    department: "AM部",
    person: "清水大輔",
    level: "medium",
    status: "in_progress",
    category: "sales",
    description: "担当者不在による対応遅延",
    customerName: "橋本様",
    customerCompany: "EFG株式会社",
    customerEmail: "hashimoto@efg-corp.co.jp",
  },
  {
    id: "ALT-013",
    datetime: "2024-01-16 15:00:00",
    keyword: "仕様変更が必要かもしれません",
    department: "営業部",
    person: "橋本真一",
    level: "high",
    status: "pending",
    category: "sales",
    description: "仕様変更による工期・費用増加リスク",
    customerName: "松本様",
    customerCompany: "HIJ株式会社",
    customerEmail: "matsumoto@hij-corp.co.jp",
  },
  {
    id: "ALT-014",
    datetime: "2024-01-16 16:30:00",
    keyword: "再度検討させていただきます",
    department: "インサイドセールス",
    person: "松本由美",
    level: "medium",
    status: "pending",
    category: "sales",
    description: "決定の先送り傾向",
    customerName: "井上様",
    customerCompany: "KLM株式会社",
    customerEmail: "inoue@klm-corp.co.jp",
  },
  {
    id: "ALT-015",
    datetime: "2024-01-17 09:15:00",
    keyword: "条件を見直す必要があります",
    department: "営業部",
    person: "井上浩二",
    level: "high",
    status: "in_progress",
    category: "sales",
    description: "契約条件の再交渉要求",
    customerName: "佐々木様",
    customerCompany: "NOP株式会社",
    customerEmail: "sasaki@nop-corp.co.jp",
  },

  // クライアント側のトラブルキーワード
  {
    id: "ALT-016",
    datetime: "2024-01-17 10:00:00",
    keyword: "○○の資料はまだでしょうか",
    department: "営業部",
    person: "佐藤一郎",
    level: "high",
    status: "pending",
    category: "client",
    description: "クライアントからの資料催促",
    customerName: "田中様",
    customerCompany: "ABC商事株式会社",
    customerEmail: "tanaka@abc-corp.co.jp",
  },
  {
    id: "ALT-017",
    datetime: "2024-01-17 11:30:00",
    keyword: "返事がありません",
    department: "AM部",
    person: "田中花子",
    level: "high",
    status: "pending",
    category: "client",
    description: "クライアントからの返答催促",
    customerName: "山田様",
    customerCompany: "XYZ株式会社",
    customerEmail: "yamada@xyz-inc.co.jp",
  },
  {
    id: "ALT-018",
    datetime: "2024-01-17 13:00:00",
    keyword: "約束の件はどうなっていますか",
    department: "インサイドセールス",
    person: "山田太郎",
    level: "medium",
    status: "in_progress",
    category: "client",
    description: "約束事項の履行確認",
    customerName: "鈴木様",
    customerCompany: "DEF株式会社",
    customerEmail: "suzuki@def-corp.co.jp",
  },
  {
    id: "ALT-019",
    datetime: "2024-01-17 14:45:00",
    keyword: "期日を過ぎています",
    department: "営業部",
    person: "鈴木次郎",
    level: "high",
    status: "pending",
    category: "client",
    description: "納期遅延の指摘",
    customerName: "高橋様",
    customerCompany: "GHI株式会社",
    customerEmail: "takahashi@ghi-corp.co.jp",
  },
  {
    id: "ALT-020",
    datetime: "2024-01-17 15:20:00",
    keyword: "話が違います",
    department: "AM部",
    person: "高橋美咲",
    level: "high",
    status: "pending",
    category: "client",
    description: "認識齟齬の発生",
    customerName: "伊藤様",
    customerCompany: "JKL株式会社",
    customerEmail: "ito@jkl-corp.co.jp",
  },
  {
    id: "ALT-021",
    datetime: "2024-01-17 16:10:00",
    keyword: "説明と異なります",
    department: "営業部",
    person: "伊藤健一",
    level: "high",
    status: "in_progress",
    category: "client",
    description: "提案内容との相違指摘",
    customerName: "渡辺様",
    customerCompany: "MNO株式会社",
    customerEmail: "watanabe@mno-corp.co.jp",
  },
  {
    id: "ALT-022",
    datetime: "2024-01-18 09:30:00",
    keyword: "対応が遅いです",
    department: "インサイドセールス",
    person: "渡辺雅子",
    level: "medium",
    status: "pending",
    category: "client",
    description: "レスポンス速度への不満",
    customerName: "加藤様",
    customerCompany: "PQR株式会社",
    customerEmail: "kato@pqr-corp.co.jp",
  },
  {
    id: "ALT-023",
    datetime: "2024-01-18 10:15:00",
    keyword: "満足できません",
    department: "AM部",
    person: "加藤直樹",
    level: "high",
    status: "pending",
    category: "client",
    description: "サービス品質への不満",
    customerName: "小林様",
    customerCompany: "STU株式会社",
    customerEmail: "kobayashi@stu-corp.co.jp",
  },
  {
    id: "ALT-024",
    datetime: "2024-01-18 11:00:00",
    keyword: "改善してください",
    department: "営業部",
    person: "小林恵子",
    level: "medium",
    status: "in_progress",
    category: "client",
    description: "サービス改善要求",
    customerName: "中村様",
    customerCompany: "VWX株式会社",
    customerEmail: "nakamura@vwx-corp.co.jp",
  },
  {
    id: "ALT-025",
    datetime: "2024-01-18 13:30:00",
    keyword: "問題があります",
    department: "インサイドセールス",
    person: "中村和也",
    level: "high",
    status: "pending",
    category: "client",
    description: "具体的問題の発生報告",
    customerName: "森田様",
    customerCompany: "YZA株式会社",
    customerEmail: "morita@yza-corp.co.jp",
  },
  {
    id: "ALT-026",
    datetime: "2024-01-18 14:20:00",
    keyword: "トラブルが発生しています",
    department: "AM部",
    person: "森田智子",
    level: "high",
    status: "pending",
    category: "client",
    description: "システムトラブル等の発生",
    customerName: "清水様",
    customerCompany: "BCD株式会社",
    customerEmail: "shimizu@bcd-corp.co.jp",
  },
  {
    id: "ALT-027",
    datetime: "2024-01-18 15:45:00",
    keyword: "契約内容と違います",
    department: "営業部",
    person: "清水大輔",
    level: "high",
    status: "in_progress",
    category: "client",
    description: "契約内容との相違指摘",
    customerName: "橋本様",
    customerCompany: "EFG株式会社",
    customerEmail: "hashimoto@efg-corp.co.jp",
  },
  {
    id: "ALT-028",
    datetime: "2024-01-18 16:30:00",
    keyword: "他社に変更を検討しています",
    department: "インサイドセールス",
    person: "橋本真一",
    level: "high",
    status: "pending",
    category: "client",
    description: "競合他社への乗り換え検討",
    customerName: "松本様",
    customerCompany: "HIJ株式会社",
    customerEmail: "matsumoto@hij-corp.co.jp",
  },
  {
    id: "ALT-029",
    datetime: "2024-01-19 09:00:00",
    keyword: "サポートが不十分です",
    department: "AM部",
    person: "松本由美",
    level: "medium",
    status: "pending",
    category: "client",
    description: "サポート体制への不満",
    customerName: "井上様",
    customerCompany: "KLM株式会社",
    customerEmail: "inoue@klm-corp.co.jp",
  },
  {
    id: "ALT-030",
    datetime: "2024-01-19 10:30:00",
    keyword: "解約を検討しています",
    department: "営業部",
    person: "井上浩二",
    level: "high",
    status: "pending",
    category: "client",
    description: "契約解約の検討表明",
    customerName: "佐々木様",
    customerCompany: "NOP株式会社",
    customerEmail: "sasaki@nop-corp.co.jp",
  },
]

// キーワード設定用のデータ
export const keywordCategories = [
  {
    category: "営業プロセス遅延",
    keywords: [
      "お見積りが完成次第",
      "来週までに回答",
      "確認が取れ次第",
      "少々お待ちください",
      "想定より時間がかかっています",
    ],
    level: "medium",
    latentType: "潜在",
    notificationDelay: 0, // 即座に通知
  },
  {
    category: "意思決定遅延",
    keywords: ["上司に確認してから", "検討中です", "社内で調整が必要", "再度検討させていただきます"],
    level: "medium",
    latentType: "潜在",
    notificationDelay: 1, // 1日後に通知
  },
  {
    category: "予算・条件問題",
    keywords: ["予算の都合で難しい", "他社と比較検討中", "条件を見直す必要", "仕様変更が必要"],
    level: "high",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },
  {
    category: "クライアント不満",
    keywords: ["資料はまだでしょうか", "返事がありません", "期日を過ぎています", "対応が遅いです", "満足できません"],
    level: "high",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },
  {
    category: "契約・認識齟齬",
    keywords: ["話が違います", "説明と異なります", "契約内容と違います", "約束の件はどうなっていますか"],
    level: "high",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },
  {
    category: "解約リスク",
    keywords: ["他社に変更を検討", "解約を検討しています", "サポートが不十分", "トラブルが発生しています"],
    level: "high",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },
]

// 営業特化テンプレートデータ（50件）
export const keywordTemplates = [
  // 新規開拓・リード獲得
  {
    id: "SALES-001",
    category: "アポイント取得困難",
    keywords: [
      "お忙しいと思いますが",
      "アポイントが取れない",
      "お時間をいただけませんでしょうか",
      "ご都合はいかがでしょうか",
      "面談の機会を",
    ],
    level: "medium",
    description: "新規顧客とのアポイント取得が困難な状況",
    usage: "新規開拓",
    salesStage: "リード獲得",
    priority: "中",
    latentType: "潜在",
    notificationDelay: 1, // 1日後に通知
  },
  {
    id: "SALES-002",
    category: "初回訪問・関係構築",
    keywords: [
      "まずは話を聞いてみます",
      "検討してみます",
      "社内で相談します",
      "また連絡します",
      "参考にさせていただきます",
    ],
    level: "low",
    description: "初回訪問後の曖昧な反応",
    usage: "新規開拓",
    salesStage: "関係構築",
    priority: "低",
    latentType: "潜在",
    notificationDelay: 2, // 2日後に通知
  },
  {
    id: "SALES-003",
    category: "ニーズ確認・ヒアリング",
    keywords: [
      "現状で満足しています",
      "特に困っていません",
      "今のところ必要ありません",
      "検討する予定はありません",
      "間に合っています",
    ],
    level: "medium",
    description: "顧客のニーズが顕在化していない状況",
    usage: "新規開拓",
    salesStage: "ニーズ確認",
    priority: "中",
    latentType: "潜在",
    notificationDelay: 3, // 3日後に通知
  },
  {
    id: "SALES-004",
    category: "競合他社の存在",
    keywords: [
      "他社も検討中です",
      "A社の提案も聞いています",
      "競合他社と比較中",
      "複数社で相見積もり",
      "他の選択肢もあります",
    ],
    level: "high",
    description: "競合他社との比較検討段階",
    usage: "新規開拓",
    salesStage: "競合比較",
    priority: "高",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },
  {
    id: "SALES-005",
    category: "予算・価格の壁",
    keywords: [
      "予算が厳しいです",
      "もう少し安くなりませんか",
      "価格が高すぎます",
      "予算オーバーです",
      "コストを抑えたいです",
    ],
    level: "high",
    description: "価格面での課題や予算制約",
    usage: "新規開拓",
    salesStage: "価格交渉",
    priority: "高",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },

  // 提案・プレゼンテーション
  {
    id: "SALES-006",
    category: "提案書・見積もり遅延",
    keywords: ["提案書を作成中です", "見積もりを調整中", "資料を準備中です", "もう少しお時間を", "来週までには"],
    level: "high",
    description: "提案書や見積もりの提出遅延",
    usage: "提案活動",
    salesStage: "提案準備",
    priority: "高",
    latentType: "潜在",
    notificationDelay: 1, // 1日後に通知
  },
  {
    id: "SALES-007",
    category: "プレゼン・デモ準備",
    keywords: ["デモの準備中です", "プレゼン資料を修正中", "実演環境を調整中", "技術者と調整中", "デモ日程を調整"],
    level: "medium",
    description: "プレゼンテーションやデモの準備段階",
    usage: "提案活動",
    salesStage: "プレゼン準備",
    priority: "中",
    latentType: "潜在",
    notificationDelay: 2, // 2日後に通知
  },
  {
    id: "SALES-008",
    category: "提案内容の修正要求",
    keywords: [
      "仕様を変更したいです",
      "要件を追加できますか",
      "カスタマイズは可能ですか",
      "別の機能も欲しいです",
      "提案を見直してください",
    ],
    level: "medium",
    description: "顧客からの提案内容修正要求",
    usage: "提案活動",
    salesStage: "提案調整",
    priority: "中",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },
  {
    id: "SALES-009",
    category: "技術的課題・制約",
    keywords: [
      "技術的に難しいです",
      "システム連携が課題",
      "既存環境との互換性",
      "セキュリティ要件が",
      "技術検証が必要",
    ],
    level: "high",
    description: "技術的な課題や制約事項",
    usage: "提案活動",
    salesStage: "技術検討",
    priority: "高",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },
  {
    id: "SALES-010",
    category: "ROI・効果の説明",
    keywords: ["効果が見えません", "ROIが不明確", "投資対効果は", "どのくらい改善されますか", "具体的なメリットは"],
    level: "high",
    description: "投資対効果や具体的効果の説明要求",
    usage: "提案活動",
    salesStage: "効果説明",
    priority: "高",
    latentType: "顕在",
    notificationDelay: 0, // 即座に通知
  },

  // 商談・交渉
  {
    id: "SALES-011",
    category: "決裁者・承認プロセス",
    keywords: ["上司の承認が必要", "役員会で検討します", "稟議を通す必要が", "決裁者が不在です", "承認プロセスが"],
    level: "medium",
    description: "決裁者や承認プロセスに関する課題",
    usage: "商談・交渉",
    salesStage: "承認プロセス",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-012",
    category: "契約条件・支払い条件",
    keywords: ["支払い条件を変更", "契約期間を短縮", "解約条件を緩和", "保証内容を拡充", "条件を見直したい"],
    level: "high",
    description: "契約条件や支払い条件の交渉",
    usage: "商談・交渉",
    salesStage: "条件交渉",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-013",
    category: "導入時期・スケジュール",
    keywords: ["導入時期を延期", "スケジュールを調整", "開始時期が未定", "準備に時間が必要", "導入計画を見直し"],
    level: "medium",
    description: "導入時期やスケジュールの調整",
    usage: "商談・交渉",
    salesStage: "スケジュール調整",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-014",
    category: "最終判断・クロージング",
    keywords: ["最終的に検討します", "もう少し時間を", "慎重に判断したい", "他の案件と優先度を", "来期に検討します"],
    level: "high",
    description: "最終判断段階での先延ばし",
    usage: "商談・交渉",
    salesStage: "クロージング",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-015",
    category: "法務・コンプライアンス",
    keywords: [
      "法務部の確認が",
      "コンプライアンス上の問題",
      "契約書の修正が",
      "規約に抵触する可能性",
      "監査対応が必要",
    ],
    level: "high",
    description: "法務やコンプライアンス関連の課題",
    usage: "商談・交渉",
    salesStage: "法務確認",
    priority: "高",
    latentType: "潜在",
  },

  // 既存顧客・アカウント管理
  {
    id: "SALES-016",
    category: "契約更新・継続",
    keywords: [
      "契約更新を検討中",
      "継続するか悩んでいます",
      "他社への切り替えも",
      "コストを見直したい",
      "契約内容を変更したい",
    ],
    level: "high",
    description: "既存契約の更新や継続に関する課題",
    usage: "既存顧客管理",
    salesStage: "契約更新",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-017",
    category: "アップセル・クロスセル",
    keywords: ["追加機能は不要", "現状で十分です", "予算がありません", "必要性を感じません", "優先度が低いです"],
    level: "medium",
    description: "アップセルやクロスセルの提案への消極的反応",
    usage: "既存顧客管理",
    salesStage: "アップセル",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-018",
    category: "顧客満足度・関係維持",
    keywords: ["期待していた効果が", "満足度が低いです", "改善してほしい点が", "サポートに不満が", "他社と比較すると"],
    level: "high",
    description: "顧客満足度や関係維持に関する課題",
    usage: "既存顧客管理",
    salesStage: "関係維持",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-019",
    category: "利用促進・活用支援",
    keywords: [
      "使いこなせていません",
      "活用方法がわからない",
      "効果的な使い方を",
      "もっと活用したいが",
      "機能を使い切れていない",
    ],
    level: "medium",
    description: "サービスの利用促進や活用支援",
    usage: "既存顧客管理",
    salesStage: "利用促進",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-020",
    category: "解約・チャーン防止",
    keywords: [
      "解約を検討しています",
      "他社に変更予定",
      "契約を終了したい",
      "継続は困難です",
      "打ち切りを考えています",
    ],
    level: "high",
    description: "解約やチャーンのリスク",
    usage: "既存顧客管理",
    salesStage: "チャーン防止",
    priority: "高",
    latentType: "潜在",
  },

  // 営業プロセス・管理
  {
    id: "SALES-021",
    category: "フォローアップ遅延",
    keywords: [
      "フォローが遅れています",
      "連絡を忘れていました",
      "追跡できていませんでした",
      "確認が遅くなり",
      "対応が後手に回り",
    ],
    level: "medium",
    description: "フォローアップや追跡の遅延",
    usage: "営業プロセス管理",
    salesStage: "フォローアップ",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-022",
    category: "情報共有・報告",
    keywords: [
      "報告が遅れています",
      "情報共有できていません",
      "進捗を把握できていない",
      "状況が不明です",
      "連携が取れていません",
    ],
    level: "medium",
    description: "チーム内での情報共有や報告の課題",
    usage: "営業プロセス管理",
    salesStage: "情報共有",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-023",
    category: "案件管理・進捗",
    keywords: [
      "案件が停滞しています",
      "進捗が芳しくありません",
      "スケジュールが遅れています",
      "計画通りに進んでいません",
      "予定より時間が",
    ],
    level: "medium",
    description: "案件管理や進捗に関する課題",
    usage: "営業プロセス管理",
    salesStage: "案件管理",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-024",
    category: "リソース・人員不足",
    keywords: ["人手が足りません", "リソースが不足", "対応しきれません", "キャパシティオーバー", "体制が不十分"],
    level: "high",
    description: "営業リソースや人員不足の課題",
    usage: "営業プロセス管理",
    salesStage: "リソース管理",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-025",
    category: "目標・KPI管理",
    keywords: ["目標達成が困難", "売上が不足しています", "KPIが未達成", "数字が厳しいです", "計画を下回っています"],
    level: "high",
    description: "売上目標やKPI達成に関する課題",
    usage: "営業プロセス管理",
    salesStage: "目標管理",
    priority: "高",
    latentType: "潜在",
  },

  // 顧客対応・サポート
  {
    id: "SALES-026",
    category: "クレーム・苦情対応",
    keywords: [
      "クレームが発生",
      "お客様からお叱りを",
      "苦情をいただきました",
      "不満を表明されました",
      "問題が発生しました",
    ],
    level: "high",
    description: "顧客からのクレームや苦情への対応",
    usage: "顧客対応",
    salesStage: "クレーム対応",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-027",
    category: "緊急対応・トラブル",
    keywords: ["緊急事態が発生", "至急対応が必要", "トラブルが起きています", "システムが停止", "業務に支障が"],
    level: "high",
    description: "緊急事態やトラブルへの対応",
    usage: "顧客対応",
    salesStage: "緊急対応",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-028",
    category: "仕様・要件変更",
    keywords: [
      "仕様を変更したい",
      "要件が変わりました",
      "追加で必要になりました",
      "当初と異なる要望",
      "変更をお願いします",
    ],
    level: "medium",
    description: "顧客からの仕様や要件変更要求",
    usage: "顧客対応",
    salesStage: "要件変更",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-029",
    category: "納期・スケジュール",
    keywords: [
      "納期を早めてほしい",
      "スケジュールを前倒し",
      "急いで対応してほしい",
      "期限が迫っています",
      "間に合わせてください",
    ],
    level: "high",
    description: "納期やスケジュールに関する要求",
    usage: "顧客対応",
    salesStage: "納期調整",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-030",
    category: "品質・パフォーマンス",
    keywords: [
      "品質に問題があります",
      "パフォーマンスが悪い",
      "期待した性能が出ない",
      "不具合が多発",
      "改善が必要です",
    ],
    level: "high",
    description: "品質やパフォーマンスに関する課題",
    usage: "顧客対応",
    salesStage: "品質改善",
    priority: "高",
    latentType: "潜在",
  },

  // 市場・競合分析
  {
    id: "SALES-031",
    category: "市場環境変化",
    keywords: [
      "市場が変化しています",
      "業界動向が変わり",
      "需要が減少しています",
      "トレンドが変わって",
      "環境が厳しくなり",
    ],
    level: "medium",
    description: "市場環境や業界動向の変化",
    usage: "市場分析",
    salesStage: "市場分析",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-032",
    category: "競合他社動向",
    keywords: [
      "競合が攻勢をかけて",
      "他社が価格を下げて",
      "新しい競合が参入",
      "競合の提案が魅力的",
      "シェアを奪われています",
    ],
    level: "high",
    description: "競合他社の動向や脅威",
    usage: "市場分析",
    salesStage: "競合分析",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-033",
    category: "価格競争・値下げ圧力",
    keywords: [
      "価格競争が激化",
      "値下げ圧力が強い",
      "もっと安くしてほしい",
      "コストダウンを要求",
      "価格で負けています",
    ],
    level: "high",
    description: "価格競争や値下げ圧力",
    usage: "市場分析",
    salesStage: "価格競争",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-034",
    category: "新技術・イノベーション",
    keywords: [
      "新技術が登場",
      "イノベーションが起きて",
      "技術革新により",
      "新しいソリューションが",
      "従来手法が古くなり",
    ],
    level: "medium",
    description: "新技術やイノベーションの影響",
    usage: "市場分析",
    salesStage: "技術動向",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-035",
    category: "顧客ニーズ変化",
    keywords: [
      "ニーズが変化しています",
      "要求レベルが上がって",
      "期待値が高くなり",
      "求められる価値が",
      "顧客の優先度が変わり",
    ],
    level: "medium",
    description: "顧客ニーズや期待値の変化",
    usage: "市場分析",
    salesStage: "ニーズ分析",
    priority: "中",
    latentType: "潜在",
  },

  // チーム・組織管理
  {
    id: "SALES-036",
    category: "チーム連携・協力",
    keywords: ["チーム連携が不十分", "部署間の協力が", "連携が取れていません", "情報共有が不足", "協力体制が"],
    level: "medium",
    description: "チーム連携や部署間協力の課題",
    usage: "チーム管理",
    salesStage: "チーム連携",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-037",
    category: "スキル・能力開発",
    keywords: ["スキルが不足しています", "能力開発が必要", "研修を受けたいです", "知識が足りません", "経験が浅くて"],
    level: "medium",
    description: "営業スキルや能力開発の必要性",
    usage: "チーム管理",
    salesStage: "スキル開発",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-038",
    category: "モチベーション・やる気",
    keywords: [
      "モチベーションが下がって",
      "やる気が出ません",
      "成果が出なくて",
      "挫折しそうです",
      "自信を失っています",
    ],
    level: "medium",
    description: "営業担当者のモチベーション低下",
    usage: "チーム管理",
    salesStage: "モチベーション管理",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-039",
    category: "業務効率・生産性",
    keywords: ["効率が悪いです", "生産性が上がりません", "時間がかかりすぎて", "無駄が多いです", "改善したいです"],
    level: "medium",
    description: "営業業務の効率性や生産性の課題",
    usage: "チーム管理",
    salesStage: "効率改善",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-040",
    category: "ツール・システム活用",
    keywords: [
      "ツールを使いこなせない",
      "システムが使いにくい",
      "機能を活用できていない",
      "操作方法がわからない",
      "効果的な使い方を",
    ],
    level: "low",
    description: "営業ツールやシステムの活用課題",
    usage: "チーム管理",
    salesStage: "ツール活用",
    priority: "低",
    latentType: "潜在",
  },

  // 特殊・その他
  {
    id: "SALES-041",
    category: "季節・時期要因",
    keywords: ["年度末で忙しく", "決算期で予算が", "夏休み期間で", "年末年始で", "繁忙期で対応が"],
    level: "low",
    description: "季節や時期による影響",
    usage: "その他",
    salesStage: "時期要因",
    priority: "低",
    latentType: "潜在",
  },
  {
    id: "SALES-042",
    category: "経済・外部環境",
    keywords: ["経済情勢が不安定", "景気が悪化して", "為替の影響で", "原材料費が上昇", "外部環境が厳しく"],
    level: "medium",
    description: "経済情勢や外部環境の影響",
    usage: "その他",
    salesStage: "外部環境",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-043",
    category: "規制・法改正",
    keywords: ["法改正の影響で", "規制が厳しくなり", "コンプライアンス対応で", "新しい基準により", "監査対応が必要"],
    level: "high",
    description: "法規制や規制変更の影響",
    usage: "その他",
    salesStage: "規制対応",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-044",
    category: "災害・不可抗力",
    keywords: ["災害の影響で", "システム障害により", "交通機関の乱れで", "不可抗力により", "予期せぬ事態で"],
    level: "high",
    description: "災害や不可抗力による影響",
    usage: "その他",
    salesStage: "不可抗力",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-045",
    category: "組織変更・人事",
    keywords: ["組織変更により", "担当者が変更", "人事異動で", "体制が変わり", "責任者が交代"],
    level: "medium",
    description: "組織変更や人事異動の影響",
    usage: "その他",
    salesStage: "組織変更",
    priority: "中",
    latentType: "潜在",
  },

  // 追加の重要パターン
  {
    id: "SALES-046",
    category: "意思決定者不在",
    keywords: ["決定権者が不在", "キーマンが出張中", "責任者が会議中", "判断できる人がいない", "決裁者に確認が必要"],
    level: "high",
    description: "意思決定者の不在による遅延",
    usage: "商談・交渉",
    salesStage: "意思決定",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-047",
    category: "情報不足・確認不足",
    keywords: ["詳細を確認中です", "情報が不足しています", "調査が必要です", "確認事項があります", "詳しく調べてから"],
    level: "medium",
    description: "情報不足や確認不足による遅延",
    usage: "営業プロセス管理",
    salesStage: "情報収集",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-048",
    category: "社内調整・合意形成",
    keywords: [
      "社内調整に時間が",
      "合意形成が困難",
      "関係者の調整が",
      "社内の意見が分かれて",
      "コンセンサスが取れない",
    ],
    level: "medium",
    description: "社内調整や合意形成の困難",
    usage: "商談・交渉",
    salesStage: "社内調整",
    priority: "中",
    latentType: "潜在",
  },
  {
    id: "SALES-049",
    category: "期待値・認識ギャップ",
    keywords: [
      "期待していたものと違う",
      "認識にギャップが",
      "想定と異なります",
      "イメージと違いました",
      "理解が不十分でした",
    ],
    level: "high",
    description: "顧客との期待値や認識のギャップ",
    usage: "顧客対応",
    salesStage: "認識合わせ",
    priority: "高",
    latentType: "潜在",
  },
  {
    id: "SALES-050",
    category: "長期検討・塩漬け案件",
    keywords: [
      "長期的に検討します",
      "時間をかけて判断",
      "慎重に検討中です",
      "じっくり考えたいです",
      "急がずに検討します",
    ],
    level: "medium",
    description: "長期検討や塩漬け状態の案件",
    usage: "商談・交渉",
    salesStage: "長期検討",
    priority: "中",
    latentType: "潜在",
  },
]

// 営業特化テンプレートカテゴリ分類
export const templateCategories = [
  { name: "新規開拓", count: 5, color: "blue", description: "新規顧客の開拓・獲得" },
  { name: "提案活動", count: 5, color: "green", description: "提案書作成・プレゼンテーション" },
  { name: "商談・交渉", count: 8, color: "purple", description: "商談進行・条件交渉" },
  { name: "既存顧客管理", count: 5, color: "orange", description: "既存顧客のフォロー・拡大" },
  { name: "営業プロセス管理", count: 5, color: "red", description: "営業活動の管理・改善" },
  { name: "顧客対応", count: 5, color: "teal", description: "顧客サポート・問題解決" },
  { name: "市場分析", count: 5, color: "pink", description: "市場・競合の分析" },
  { name: "チーム管理", count: 5, color: "indigo", description: "営業チームの管理・育成" },
  { name: "その他", count: 7, color: "gray", description: "その他の営業関連課題" },
]

// アラート詳細データ（全30件）
export const alertDetailData: { [key: string]: any } = {
  "ALT-001": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 新システム導入のお見積りについて",
        timestamp: "2024-01-15 09:30:15",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "田中様（ABC商事）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-12 14:30",
        tool: "gmail",
        content:
          "佐藤様<br/><br/>いつもお世話になっております。<br/>先日お話しいただいた新システム導入の件でお見積りをお願いしたいのですが、いつ頃いただけますでしょうか？<br/><br/>来週の役員会で検討したいと考えておりますので、可能であれば今週中にいただけると助かります。<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "佐藤一郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-12 16:45",
        tool: "gmail",
        content:
          "田中様<br/><br/>お疲れ様です。<br/>お見積りの件、承知いたしました。<br/><br/>詳細な要件を確認させていただき、正確なお見積りを作成いたします。<br/>来週の役員会に間に合うよう、今週末までにはお送りいたします。<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "client",
        name: "田中様（ABC商事）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 09:15",
        tool: "gmail",
        content:
          "佐藤様<br/><br/>お疲れ様です。<br/>先週お約束いただいたお見積りの件でご連絡いたします。<br/><br/>まだお見積りをいただけていないのですが、進捗はいかがでしょうか？<br/>明日の役員会で検討予定でしたが、資料が揃わない状況です。<br/><br/>ご確認のほど、よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "佐藤一郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 09:30",
        tool: "gmail",
        content:
          "田中様<br/><br/>申し訳ございません。<br/>お見積りが完成次第送付しますので、もう少しお待ちください。<br/><br/>技術部門との調整に予想以上に時間がかかっており、本日中には必ずお送りいたします。<br/><br/>ご迷惑をおかけして申し訳ございません。",
        isAlert: true,
      },
    ],
  },
  "ALT-002": {
    detections: [
      {
        tool: "chat",
        toolName: "Google Chat",
        location: "チャンネル: #インサイドセールス",
        timestamp: "2024-01-15 10:15:30",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "山田マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 09:00",
        tool: "chat",
        content: "田中さん、XYZ社の件はどうなってる？先週プレゼンしたよね？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "田中花子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 09:30",
        tool: "chat",
        content: "はい、プレゼンは好評でした。ただ、決裁者の方が出張中で最終判断が保留になっています。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "other",
        name: "山田マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 09:45",
        tool: "chat",
        content: "いつ頃回答もらえそう？四半期末が近いから急ぎたいんだけど。",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "田中花子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 10:15",
        tool: "chat",
        content: "来週までに回答しますと先方からお返事いただいています。具体的な日程は調整中です。",
        isAlert: true,
      },
    ],
  },
  "ALT-003": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 契約条件について",
        timestamp: "2024-01-15 11:00:45",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "鈴木様（DEF株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-14 15:00",
        tool: "gmail",
        content:
          "山田様<br/><br/>お疲れ様です。<br/>ご提案いただいた契約条件について検討いたしました。<br/><br/>基本的には問題ないのですが、支払い条件について少し調整が必要かもしれません。<br/>月末締め翌月末払いを翌々月末払いに変更できますでしょうか？<br/><br/>ご検討のほど、よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "山田太郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-14 17:30",
        tool: "gmail",
        content:
          "鈴木様<br/><br/>ご連絡ありがとうございます。<br/>支払い条件の変更について承知いたしました。<br/><br/>社内で検討させていただき、明日までにはご回答いたします。<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "client",
        name: "鈴木様（DEF株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 10:30",
        tool: "gmail",
        content:
          "山田様<br/><br/>昨日の件、いかがでしょうか？<br/>来週から新年度の予算計画に入るため、早めに確定したいと考えております。<br/><br/>ご確認をお願いいたします。",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "山田太郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 11:00",
        tool: "gmail",
        content:
          "鈴木様<br/><br/>申し訳ございません。<br/>上司に確認してから連絡しますので、もう少しお時間をいただけますでしょうか。<br/><br/>本日中には必ずご回答いたします。<br/><br/>よろしくお願いいたします。",
        isAlert: true,
      },
    ],
  },
  "ALT-004": {
    detections: [
      {
        tool: "chat",
        toolName: "Google Chat",
        location: "ダイレクトメッセージ",
        timestamp: "2024-01-15 13:45:20",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "佐藤部長",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 13:00",
        tool: "chat",
        content: "鈴木さん、GHI社の新規案件の進捗はどう？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "鈴木次郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 13:15",
        tool: "chat",
        content: "先週プレゼンを行い、先方からは前向きな反応をいただいています。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "other",
        name: "佐藤部長",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 13:30",
        tool: "chat",
        content: "それで、いつ頃決まりそう？今四半期の数字に入れられる？",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "鈴木次郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 13:45",
        tool: "chat",
        content: "まだ検討中ですとのことで、具体的なスケジュールは確認できていません。来週再度確認します。",
        isAlert: true,
      },
    ],
  },
  "ALT-005": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 新サービス導入について",
        timestamp: "2024-01-15 14:20:30",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "佐々木様（JKL商事）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-13 10:00",
        tool: "gmail",
        content:
          "高橋様<br/><br/>いつもお世話になっております。<br/>先日ご提案いただいた新サービスについて、社内で検討いたしました。<br/><br/>サービス内容については非常に魅力的で、ぜひ導入したいと考えております。<br/>ただ、価格面で少し課題があります。<br/><br/>お見積りをいただけますでしょうか？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "高橋美咲",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-13 14:00",
        tool: "gmail",
        content:
          "佐々木様<br/><br/>ご検討いただきありがとうございます。<br/>お見積りの件、承知いたしました。<br/><br/>詳細な要件をお聞かせいただき、最適なプランをご提案させていただきます。<br/>来週お伺いさせていただけますでしょうか？<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "client",
        name: "佐々木様（JKL商事）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 13:30",
        tool: "gmail",
        content:
          "高橋様<br/><br/>先日お伺いいただき、ありがとうございました。<br/>詳細なお見積りをお待ちしております。<br/><br/>ただ、正直なところ当初想定していた予算を大幅に超えており、導入が難しい状況です。<br/>何か良い方法はありますでしょうか？",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "高橋美咲",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 14:20",
        tool: "gmail",
        content:
          "佐々木様<br/><br/>ご連絡ありがとうございます。<br/>予算の都合で難しいかもしれませんが、段階的な導入プランもご用意できます。<br/><br/>まずは基本機能から始めて、効果を確認してから拡張していく方法はいかがでしょうか？<br/><br/>再度ご提案させていただきます。",
        isAlert: true,
      },
    ],
  },
  "ALT-006": {
    detections: [
      {
        tool: "chat",
        toolName: "Google Chat",
        location: "チャンネル: #インサイドセールス",
        timestamp: "2024-01-15 15:30:15",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "田中マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 14:00",
        tool: "chat",
        content: "伊藤さん、MNO社の案件はどうなってる？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "伊藤健一",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 14:30",
        tool: "chat",
        content: "プレゼンは好評でしたが、決定には時間がかかりそうです。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "other",
        name: "田中マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 15:00",
        tool: "chat",
        content: "何が課題になってるの？",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "伊藤健一",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 15:30",
        tool: "chat",
        content: "他社と比較検討中ですとのことで、A社とB社の提案も並行して検討されています。価格面で競合が厳しいです。",
        isAlert: true,
      },
    ],
  },
  "ALT-007": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: プロジェクト開始について",
        timestamp: "2024-01-15 16:10:45",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "田村様（PQR株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-14 11:00",
        tool: "gmail",
        content:
          "渡辺様<br/><br/>お疲れ様です。<br/>来月からのプロジェクト開始に向けて準備を進めております。<br/><br/>キックオフミーティングの日程を調整したいのですが、来週のご都合はいかがでしょうか？<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "渡辺雅子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-14 15:30",
        tool: "gmail",
        content:
          "田村様<br/><br/>ご連絡ありがとうございます。<br/>キックオフミーティングの件、承知いたしました。<br/><br/>来週でしたら火曜日の午後が空いております。<br/>詳細な議題も含めて調整させていただきます。<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "client",
        name: "田村様（PQR株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 15:00",
        tool: "gmail",
        content:
          "渡辺様<br/><br/>火曜日の件、ありがとうございます。<br/>ただ、プロジェクトメンバーの調整が必要で、全員の都合を合わせるのに時間がかかっています。<br/><br/>開始時期について相談があります。",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "渡辺雅子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 16:10",
        tool: "gmail",
        content:
          "田村様<br/><br/>承知いたしました。<br/>社内で調整が必要ですので、メンバーの都合がつき次第ご連絡いたします。<br/><br/>開始時期についても柔軟に対応いたします。<br/><br/>よろしくお願いいたします。",
        isAlert: true,
      },
    ],
  },
}

// 営業単位・部門別アラートデータ
export const salesPersonAlertData = {
  weekly: [
    { name: "佐藤一郎", alerts: 12, resolved: 8, pending: 4, department: "営業部", previousAlerts: 10, previousResolved: 7, previousPending: 3 },
    { name: "田中花子", alerts: 8, resolved: 6, pending: 2, department: "インサイドセールス", previousAlerts: 7, previousResolved: 5, previousPending: 2 },
    { name: "山田太郎", alerts: 15, resolved: 10, pending: 5, department: "営業部", previousAlerts: 13, previousResolved: 9, previousPending: 4 },
    { name: "鈴木次郎", alerts: 6, resolved: 5, pending: 1, department: "AM部", previousAlerts: 5, previousResolved: 4, previousPending: 1 },
    { name: "高橋美咲", alerts: 9, resolved: 7, pending: 2, department: "営業部", previousAlerts: 8, previousResolved: 6, previousPending: 2 },
    { name: "伊藤健一", alerts: 11, resolved: 8, pending: 3, department: "インサイドセールス", previousAlerts: 10, previousResolved: 7, previousPending: 3 },
    { name: "渡辺雅子", alerts: 7, resolved: 6, pending: 1, department: "営業部", previousAlerts: 6, previousResolved: 5, previousPending: 1 },
    { name: "加藤直樹", alerts: 10, resolved: 7, pending: 3, department: "AM部", previousAlerts: 9, previousResolved: 6, previousPending: 3 },
  ],
  monthly: [
    { name: "佐藤一郎", alerts: 45, resolved: 32, pending: 13, department: "営業部", previousAlerts: 41, previousResolved: 29, previousPending: 12 },
    { name: "田中花子", alerts: 28, resolved: 22, pending: 6, department: "インサイドセールス", previousAlerts: 25, previousResolved: 19, previousPending: 6 },
    { name: "山田太郎", alerts: 52, resolved: 38, pending: 14, department: "営業部", previousAlerts: 48, previousResolved: 35, previousPending: 13 },
    { name: "鈴木次郎", alerts: 22, resolved: 19, pending: 3, department: "AM部", previousAlerts: 20, previousResolved: 17, previousPending: 3 },
    { name: "高橋美咲", alerts: 35, resolved: 28, pending: 7, department: "営業部", previousAlerts: 32, previousResolved: 25, previousPending: 7 },
    { name: "伊藤健一", alerts: 41, resolved: 33, pending: 8, department: "インサイドセールス", previousAlerts: 38, previousResolved: 30, previousPending: 8 },
    { name: "渡辺雅子", alerts: 29, resolved: 24, pending: 5, department: "営業部", previousAlerts: 27, previousResolved: 22, previousPending: 5 },
    { name: "加藤直樹", alerts: 38, resolved: 31, pending: 7, department: "AM部", previousAlerts: 35, previousResolved: 28, previousPending: 7 },
  ],
  quarterly: [
    { name: "佐藤一郎", alerts: 142, resolved: 108, pending: 34, department: "営業部", previousAlerts: 130, previousResolved: 99, previousPending: 31 },
    { name: "田中花子", alerts: 89, resolved: 71, pending: 18, department: "インサイドセールス", previousAlerts: 81, previousResolved: 65, previousPending: 16 },
    { name: "山田太郎", alerts: 165, resolved: 125, pending: 40, department: "営業部", previousAlerts: 150, previousResolved: 114, previousPending: 36 },
    { name: "鈴木次郎", alerts: 68, resolved: 58, pending: 10, department: "AM部", previousAlerts: 62, previousResolved: 53, previousPending: 9 },
    { name: "高橋美咲", alerts: 112, resolved: 89, pending: 23, department: "営業部", previousAlerts: 102, previousResolved: 81, previousPending: 21 },
    { name: "伊藤健一", alerts: 128, resolved: 102, pending: 26, department: "インサイドセールス", previousAlerts: 117, previousResolved: 93, previousPending: 24 },
    { name: "渡辺雅子", alerts: 95, resolved: 78, pending: 17, department: "営業部", previousAlerts: 87, previousResolved: 71, previousPending: 16 },
    { name: "加藤直樹", alerts: 118, resolved: 96, pending: 22, department: "AM部", previousAlerts: 108, previousResolved: 88, previousPending: 20 },
  ],
  yearly: [
    { name: "佐藤一郎", alerts: 580, resolved: 445, pending: 135, department: "営業部", previousAlerts: 540, previousResolved: 410, previousPending: 130 },
    { name: "田中花子", alerts: 365, resolved: 295, pending: 70, department: "インサイドセールス", previousAlerts: 340, previousResolved: 270, previousPending: 70 },
    { name: "山田太郎", alerts: 672, resolved: 512, pending: 160, department: "営業部", previousAlerts: 630, previousResolved: 480, previousPending: 150 },
    { name: "鈴木次郎", alerts: 278, resolved: 238, pending: 40, department: "AM部", previousAlerts: 260, previousResolved: 220, previousPending: 40 },
    { name: "高橋美咲", alerts: 458, resolved: 368, pending: 90, department: "営業部", previousAlerts: 430, previousResolved: 340, previousPending: 90 },
    { name: "伊藤健一", alerts: 525, resolved: 420, pending: 105, department: "インサイドセールス", previousAlerts: 490, previousResolved: 390, previousPending: 100 },
    { name: "渡辺雅子", alerts: 385, resolved: 315, pending: 70, department: "営業部", previousAlerts: 360, previousResolved: 290, previousPending: 70 },
    { name: "加藤直樹", alerts: 485, resolved: 395, pending: 90, department: "AM部", previousAlerts: 450, previousResolved: 360, previousPending: 90 },
  ],
}

export const departmentAlertData = {
  weekly: [
    { name: "営業部", alerts: 43, resolved: 31, pending: 12, members: 4, previousAlerts: 39, previousResolved: 28, previousPending: 11 },
    { name: "インサイドセールス", alerts: 19, resolved: 14, pending: 5, members: 3, previousAlerts: 17, previousResolved: 12, previousPending: 5 },
    { name: "AM部", alerts: 16, resolved: 12, pending: 4, members: 2, previousAlerts: 15, previousResolved: 11, previousPending: 4 },
  ],
  monthly: [
    { name: "営業部", alerts: 161, resolved: 122, pending: 39, members: 4, previousAlerts: 150, previousResolved: 114, previousPending: 36 },
    { name: "インサイドセールス", alerts: 69, resolved: 55, pending: 14, members: 3, previousAlerts: 63, previousResolved: 50, previousPending: 13 },
    { name: "AM部", alerts: 60, resolved: 50, pending: 10, members: 2, previousAlerts: 56, previousResolved: 47, previousPending: 9 },
  ],
  quarterly: [
    { name: "営業部", alerts: 514, resolved: 400, pending: 114, members: 4, previousAlerts: 480, previousResolved: 374, previousPending: 106 },
    { name: "インサイドセールス", alerts: 217, resolved: 173, pending: 44, members: 3, previousAlerts: 202, previousResolved: 161, previousPending: 41 },
    { name: "AM部", alerts: 186, resolved: 154, pending: 32, members: 2, previousAlerts: 174, previousResolved: 144, previousPending: 30 },
  ],
  yearly: [
    { name: "営業部", alerts: 2095, resolved: 1640, pending: 455, members: 4, previousAlerts: 1950, previousResolved: 1520, previousPending: 430 },
    { name: "インサイドセールス", alerts: 890, resolved: 715, pending: 175, members: 3, previousAlerts: 820, previousResolved: 650, previousPending: 170 },
    { name: "AM部", alerts: 763, resolved: 633, pending: 130, members: 2, previousAlerts: 710, previousResolved: 590, previousPending: 120 },
  ],
}

export const timeSeriesData = {
  weekly: [
    { period: "月", alerts: 12, resolved: 8, pending: 4, previousAlerts: 10, previousResolved: 7, previousPending: 3 },
    { period: "火", alerts: 15, resolved: 11, pending: 4, previousAlerts: 13, previousResolved: 9, previousPending: 4 },
    { period: "水", alerts: 8, resolved: 6, pending: 2, previousAlerts: 9, previousResolved: 6, previousPending: 3 },
    { period: "木", alerts: 18, resolved: 13, pending: 5, previousAlerts: 16, previousResolved: 12, previousPending: 4 },
    { period: "金", alerts: 11, resolved: 9, pending: 2, previousAlerts: 12, previousResolved: 8, previousPending: 4 },
    { period: "土", alerts: 6, resolved: 4, pending: 2, previousAlerts: 7, previousResolved: 5, previousPending: 2 },
    { period: "日", alerts: 8, resolved: 6, pending: 2, previousAlerts: 9, previousResolved: 6, previousPending: 3 },
  ],
  monthly: [
    { period: "第1週", alerts: 78, resolved: 57, pending: 21, previousAlerts: 72, previousResolved: 53, previousPending: 19 },
    { period: "第2週", alerts: 85, resolved: 64, pending: 21, previousAlerts: 79, previousResolved: 58, previousPending: 21 },
    { period: "第3週", alerts: 72, resolved: 55, pending: 17, previousAlerts: 68, previousResolved: 51, previousPending: 17 },
    { period: "第4週", alerts: 90, resolved: 68, pending: 22, previousAlerts: 84, previousResolved: 62, previousPending: 22 },
  ],
  quarterly: [
    { period: "1月", alerts: 325, resolved: 244, pending: 81, previousAlerts: 298, previousResolved: 225, previousPending: 73 },
    { period: "2月", alerts: 298, resolved: 228, pending: 70, previousAlerts: 275, previousResolved: 208, previousPending: 67 },
    { period: "3月", alerts: 294, resolved: 225, pending: 69, previousAlerts: 268, previousResolved: 201, previousPending: 67 },
  ],
  yearly: [
    { period: "Q1", alerts: 917, resolved: 697, pending: 220, previousAlerts: 841, previousResolved: 634, previousPending: 207 },
    { period: "Q2", alerts: 856, resolved: 658, pending: 198, previousAlerts: 789, previousResolved: 598, previousPending: 191 },
    { period: "Q3", alerts: 923, resolved: 712, pending: 211, previousAlerts: 845, previousResolved: 642, previousPending: 203 },
    { period: "Q4", alerts: 1052, resolved: 821, pending: 231, previousAlerts: 967, previousResolved: 745, previousPending: 222 },
  ],
}

// アラート詳細のチャットケースデータ
export const alertChatCases: Record<string, {
  detections: Array<{
    tool: string;
    toolName: string;
    location: string;
    timestamp: string;
  }>;
  messages: Array<{
    id: number;
    sender: "self" | "other" | "client";
    name: string;
    avatar: string;
    timestamp: string;
    tool: string;
    content: string;
    isAlert: boolean;
  }>;
}> = {
  "ALT-001": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 見積もりについて",
        timestamp: "2024-01-15 09:30:25",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "山本様（ABC株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-01 14:00",
        tool: "gmail",
        content: "佐藤様<br/><br/>お疲れ様です。<br/>先日ご提案いただいたシステムの見積もりについて、詳細を確認させていただきたいと思います。<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "佐藤一郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-01 16:30",
        tool: "gmail",
        content: "山本様<br/><br/>ご連絡ありがとうございます。<br/>見積もりについて、お見積りが完成次第送付します。<br/><br/>よろしくお願いいたします。",
        isAlert: true,
      },
      {
        id: 3,
        sender: "client",
        name: "山本様（ABC株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 09:00",
        tool: "gmail",
        content: "佐藤様<br/><br/>見積もりの件、いかがでしょうか？<br/>2週間ほど経過いたしましたが、まだ届いておりません。<br/><br/>ご確認いただけますでしょうか。",
        isAlert: false,
      },
    ],
  },
  "ALT-002": {
    detections: [
      {
        tool: "chat",
        toolName: "Slack",
        location: "#sales-channel",
        timestamp: "2024-01-15 10:15:10",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "田中マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 09:00",
        tool: "chat",
        content: "田中さん、DEF社の件はどうなってる？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "田中花子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 10:15",
        tool: "chat",
        content: "来週までに回答しますとのことです。",
        isAlert: true,
      },
    ],
  },
  "ALT-003": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 契約条件について",
        timestamp: "2024-01-15 11:00:30",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "佐々木様（GHI株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 10:30",
        tool: "gmail",
        content: "山田様<br/><br/>契約条件について、いくつか質問があります。<br/>価格の交渉余地はありますでしょうか？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "山田太郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 11:00",
        tool: "gmail",
        content: "佐々木様<br/><br/>価格について、上司に確認してから連絡します。<br/><br/>よろしくお願いいたします。",
        isAlert: true,
      },
    ],
  },
  "ALT-004": {
    detections: [
      {
        tool: "chat",
        toolName: "Teams",
        location: "営業部チャット",
        timestamp: "2024-01-15 13:45:15",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "鈴木マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 13:30",
        tool: "chat",
        content: "鈴木さん、JKL社の案件はどう？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "鈴木次郎",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 13:45",
        tool: "chat",
        content: "検討中です。",
        isAlert: true,
      },
    ],
  },
  "ALT-005": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: プロジェクト提案について",
        timestamp: "2024-01-15 14:20:45",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "中村様（MNO株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 14:00",
        tool: "gmail",
        content: "高橋様<br/><br/>プロジェクト提案について検討いたしました。<br/>内容は非常に興味深いのですが、予算の都合で難しいかもしれません。<br/><br/>何か方法はありますでしょうか？",
        isAlert: true,
      },
    ],
  },
  "ALT-006": {
    detections: [
      {
        tool: "chat",
        toolName: "Slack",
        location: "#sales-channel",
        timestamp: "2024-01-15 15:30:15",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "田中マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 14:00",
        tool: "chat",
        content: "伊藤さん、MNO社の案件はどうなってる？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "伊藤健一",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 14:30",
        tool: "chat",
        content: "プレゼンは好評でしたが、決定には時間がかかりそうです。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "other",
        name: "田中マネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 15:00",
        tool: "chat",
        content: "何が課題になってるの？",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "伊藤健一",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 15:30",
        tool: "chat",
        content: "他社と比較検討中ですとのことで、A社とB社の提案も並行して検討されています。価格面で競合が厳しいです。",
        isAlert: true,
      },
    ],
  },
  "ALT-007": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: プロジェクト開始について",
        timestamp: "2024-01-15 16:10:45",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "田村様（PQR株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-14 11:00",
        tool: "gmail",
        content:
          "渡辺様<br/><br/>お疲れ様です。<br/>来月からのプロジェクト開始に向けて準備を進めております。<br/><br/>キックオフミーティングの日程を調整したいのですが、来週のご都合はいかがでしょうか？<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "渡辺雅子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-14 15:30",
        tool: "gmail",
        content:
          "田村様<br/><br/>ご連絡ありがとうございます。<br/>キックオフミーティングの件、承知いたしました。<br/><br/>来週でしたら火曜日の午後が空いております。<br/>詳細な議題も含めて調整させていただきます。<br/><br/>よろしくお願いいたします。",
        isAlert: false,
      },
      {
        id: 3,
        sender: "client",
        name: "田村様（PQR株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 15:00",
        tool: "gmail",
        content:
          "渡辺様<br/><br/>火曜日の件、ありがとうございます。<br/>ただ、プロジェクトメンバーの調整が必要で、全員の都合を合わせるのに時間がかかっています。<br/><br/>開始時期について相談があります。",
        isAlert: false,
      },
      {
        id: 4,
        sender: "self",
        name: "渡辺雅子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-15 16:10",
        tool: "gmail",
        content:
          "田村様<br/><br/>承知いたしました。<br/>社内で調整が必要ですので、メンバーの都合がつき次第ご連絡いたします。<br/><br/>開始時期についても柔軟に対応いたします。<br/><br/>よろしくお願いいたします。",
        isAlert: true,
      },
    ],
  },
  "ALT-008": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: システム障害について",
        timestamp: "2024-01-16 09:00:20",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "木村様（STU株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 08:30",
        tool: "gmail",
        content: "加藤様<br/><br/>昨日からシステムにアクセスできない状況が続いています。<br/>緊急で対応をお願いいたします。",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "加藤直樹",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 09:00",
        tool: "gmail",
        content: "木村様<br/><br/>申し訳ございませんが、現在技術チームが原因を調査中です。<br/>詳細が判明次第、すぐにご連絡いたします。",
        isAlert: true,
      },
    ],
  },
  "ALT-009": {
    detections: [
      {
        tool: "chat",
        toolName: "Teams",
        location: "プロジェクト管理",
        timestamp: "2024-01-16 10:30:35",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "プロジェクトマネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 10:00",
        tool: "chat",
        content: "小林さん、VWX社のプロジェクト進捗はどう？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "小林恵子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 10:30",
        tool: "chat",
        content: "想定より時間がかかっています。仕様変更の影響で、完了予定が2週間ほど遅れる見込みです。",
        isAlert: true,
      },
    ],
  },
  "ALT-010": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 資料請求について",
        timestamp: "2024-01-16 11:45:50",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "斎藤様（YZA株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 11:00",
        tool: "gmail",
        content: "中村様<br/><br/>先日ご依頼いただいた資料について、確認が取れ次第ご連絡します。<br/><br/>よろしくお願いいたします。",
        isAlert: true,
      },
    ],
  },
  "ALT-011": {
    detections: [
      {
        tool: "chat",
        toolName: "Slack",
        location: "#customer-support",
        timestamp: "2024-01-16 13:20:10",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "山田様（BCD株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 13:00",
        tool: "chat",
        content: "森田さん、先ほどの件について確認できましたか？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "森田智子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 13:20",
        tool: "chat",
        content: "少々お待ちください。現在確認中です。",
        isAlert: true,
      },
    ],
  },
  "ALT-012": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 打ち合わせについて",
        timestamp: "2024-01-16 14:15:25",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "佐藤様（EFG株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 14:00",
        tool: "gmail",
        content: "清水様<br/><br/>明日の打ち合わせについて、担当者が不在のため、日程を変更させていただけますでしょうか？<br/><br/>よろしくお願いいたします。",
        isAlert: true,
      },
    ],
  },
  "ALT-013": {
    detections: [
      {
        tool: "chat",
        toolName: "Teams",
        location: "開発チーム",
        timestamp: "2024-01-16 15:00:40",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "開発リーダー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 14:30",
        tool: "chat",
        content: "橋本さん、HIJ社の要件確認はどうなってる？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "橋本真一",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 15:00",
        tool: "chat",
        content: "クライアントから仕様変更が必要かもしれませんとの連絡がありました。詳細を確認中です。",
        isAlert: true,
      },
    ],
  },
  "ALT-014": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 提案書について",
        timestamp: "2024-01-16 16:30:15",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "田中様（KLM株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-16 16:00",
        tool: "gmail",
        content: "松本様<br/><br/>先日いただいた提案書について、社内で再度検討させていただきます。<br/><br/>ご回答まで少々お時間をいただけますでしょうか？",
        isAlert: true,
      },
    ],
  },
  "ALT-015": {
    detections: [
      {
        tool: "chat",
        toolName: "Slack",
        location: "#contract-negotiation",
        timestamp: "2024-01-17 09:15:30",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "法務担当",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 09:00",
        tool: "chat",
        content: "井上さん、NOP社との契約交渉はどうなってる？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "井上浩二",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 09:15",
        tool: "chat",
        content: "クライアントから条件を見直す必要がありますとの要求がありました。価格と納期の再交渉が必要です。",
        isAlert: true,
      },
    ],
  },
  "ALT-016": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: 資料の件について",
        timestamp: "2024-01-17 10:00:45",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "佐藤様（QRS株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 09:30",
        tool: "gmail",
        content: "佐藤様<br/><br/>先日ご依頼いただいた○○の資料はまだでしょうか？<br/>急ぎで必要になっております。<br/><br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
  "ALT-017": {
    detections: [
      {
        tool: "chat",
        toolName: "Teams",
        location: "顧客対応",
        timestamp: "2024-01-17 11:30:20",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "山田様（TUV株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 11:00",
        tool: "chat",
        content: "田中さん、先ほどの件について返事がありませんが、いかがでしょうか？",
        isAlert: true,
      },
    ],
  },
  "ALT-018": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 約束の件について",
        timestamp: "2024-01-17 13:00:35",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "鈴木様（WXY株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 12:30",
        tool: "gmail",
        content: "山田様<br/><br/>先日お約束いただいた件はどうなっていますか？<br/>期限が迫っております。<br/><br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
  "ALT-019": {
    detections: [
      {
        tool: "chat",
        toolName: "Slack",
        location: "#sales-support",
        timestamp: "2024-01-17 14:30:50",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "営業サポート",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 14:00",
        tool: "chat",
        content: "高橋さん、ZAB社からの問い合わせについて、まだ返答していませんが、いかがでしょうか？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "高橋美咲",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 14:30",
        tool: "chat",
        content: "まだ返答していません。明日中に回答いたします。",
        isAlert: true,
      },
    ],
  },
  "ALT-020": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 進捗について",
        timestamp: "2024-01-17 15:45:10",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "田中様（CDE株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-17 15:00",
        tool: "gmail",
        content: "伊藤様<br/><br/>プロジェクトの進捗について、まだ進捗がありませんが、いかがでしょうか？<br/>スケジュールに遅れが出ています。<br/><br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
  "ALT-021": {
    detections: [
      {
        tool: "chat",
        toolName: "Teams",
        location: "プロジェクト管理",
        timestamp: "2024-01-18 09:00:25",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "プロジェクトマネージャー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 08:30",
        tool: "chat",
        content: "渡辺さん、FGH社のプロジェクトは順調ですか？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "渡辺雅子",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 09:00",
        tool: "chat",
        content: "まだ進捗がありません。技術的な課題があり、解決に時間がかかっています。",
        isAlert: true,
      },
    ],
  },
  "ALT-022": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 確認について",
        timestamp: "2024-01-18 10:15:40",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "佐々木様（IJK株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 09:45",
        tool: "gmail",
        content: "加藤様<br/><br/>先日お送りいただいた資料について、まだ確認が取れていませんが、いかがでしょうか？<br/>内容を確認したいと思います。<br/><br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
  "ALT-023": {
    detections: [
      {
        tool: "chat",
        toolName: "Slack",
        location: "#customer-service",
        timestamp: "2024-01-18 11:30:15",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "木村様（LMN株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 11:00",
        tool: "chat",
        content: "小林さん、先ほどの件について、まだ回答がありませんが、いかがでしょうか？",
        isAlert: true,
      },
    ],
  },
  "ALT-024": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 対応について",
        timestamp: "2024-01-18 13:45:30",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "中村様（OPQ株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 13:00",
        tool: "gmail",
        content: "森田様<br/><br/>先日ご報告いただいた件について、まだ対応がありませんが、いかがでしょうか？<br/>緊急で対応が必要です。<br/><br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
  "ALT-025": {
    detections: [
      {
        tool: "chat",
        toolName: "Teams",
        location: "営業部",
        timestamp: "2024-01-18 14:30:45",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "営業部長",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 14:00",
        tool: "chat",
        content: "清水さん、RST社の案件はどうなってる？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "清水大輔",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 14:30",
        tool: "chat",
        content: "まだ進捗がありません。クライアントからの返答を待っている状況です。",
        isAlert: true,
      },
    ],
  },
  "ALT-026": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 連絡について",
        timestamp: "2024-01-18 15:15:20",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "斎藤様（UVW株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 14:45",
        tool: "gmail",
        content: "橋本様<br/><br/>先日お約束いただいた件について、まだ連絡がありませんが、いかがでしょうか？<br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
  "ALT-027": {
    detections: [
      {
        tool: "chat",
        toolName: "Slack",
        location: "#project-updates",
        timestamp: "2024-01-18 16:00:35",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "other",
        name: "プロジェクトリーダー",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 15:30",
        tool: "chat",
        content: "松本さん、XYZ社のプロジェクト進捗はどう？",
        isAlert: false,
      },
      {
        id: 2,
        sender: "self",
        name: "松本由美",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-18 16:00",
        tool: "chat",
        content: "まだ進捗がありません。技術的な課題があり、解決策を検討中です。",
        isAlert: true,
      },
    ],
  },
  "ALT-028": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 回答について",
        timestamp: "2024-01-19 09:30:50",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "山田様（ABC株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-19 09:00",
        tool: "gmail",
        content: "井上様<br/><br/>先日お送りいただいた質問について、まだ回答がありませんが、いかがでしょうか？<br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
  "ALT-029": {
    detections: [
      {
        tool: "chat",
        toolName: "Teams",
        location: "顧客対応",
        timestamp: "2024-01-19 10:45:15",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "田中様（DEF株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-19 10:15",
        tool: "chat",
        content: "高橋さん、先ほどの件について、まだ確認が取れていませんが、いかがでしょうか？",
        isAlert: true,
      },
    ],
  },
  "ALT-030": {
    detections: [
      {
        tool: "gmail",
        toolName: "Gmail",
        location: "件名: Re: 対応状況について",
        timestamp: "2024-01-19 11:30:25",
      },
    ],
    messages: [
      {
        id: 1,
        sender: "client",
        name: "佐藤様（GHI株式会社）",
        avatar: "/placeholder.svg?height=32&width=32",
        timestamp: "2024-01-19 11:00",
        tool: "gmail",
        content: "伊藤様<br/><br/>先日ご報告いただいた件について、まだ対応状況が分かりませんが、いかがでしょうか？<br/>ご確認いただけますでしょうか。",
        isAlert: true,
      },
    ],
  },
}
